### ISSUE TITLE
token transfers with the -o flag

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#133] opened 2024-07-03 10:10 UTC
I've compared the output of the `token transfers fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974` with the `token transfers fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 -o` (and then also with the `token transfers fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 -o True`, to be sure I'm doing it right) and there is no difference on my side between them.

If I understand it right the expected output for the `token transfers fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 -o` should include the following txids only:
- 40000fd970a4b3b8c504a04293119c2391b382f0d6719f29fa23787803b3e1ea
- 94666fe1616c9825e849a30b4d525facf4b0485f322857b743abcf0ee233f262
- 49cabb53871e588561a46daf2e2427b01adaaca70a7cb44fcf0ed3316ff9a811

(I've extrapolated this txids by comparing the `token transfers fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974` with the `token transfers fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 -s` output, which includes the above txids, but I don't know whether they are really the valid one or not).

**Comment by d5000** [comment] 2024-07-09 00:22
Confirmed, thanks. Fixed in commit 82ae216 and closed because the bug was a small one and its fix was quite obvious. I will do so from now on in these cases (this is normal in open source projects) to keep the number of open issues low.

**Closed by d5000** 2024-07-09 00:22 UTC
Labels: anomaly
