### ISSUE TITLE
Would it make sense suppressing vanilla command?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#168] opened 2024-08-01 09:40 UTC
I was thinking about [the list of vanilla](https://github.com/slimcoin-project/pacli/issues/74#vanilla) commands I've got from you some month ago.
What if we suppress them altogether when the compatibility mode is set to `false`?
That would limit the number of the available commands making it more clear for advanced and intermediate users which commands are meant to be used in our context.
In this way we'd also avoid delivering the code that is not fully tested by us. Otherwise the bugs and the unexpected error messages we are not even aware of may be considered our creation by the users which may create not such a good image for the code we are about to deliver.

**Comment by d5000** [comment] 2024-08-08 20:24
I've not started working on this, but a small comment as you mentioned this issue in another one.

The idea is good, it also crossed my mind. However, it may be complicated to implement this, because the help of Fire (the base of Pacli) will always show the vanilla commands as well.

I'm not decided still. The other strategy is to simply fix the bugs (and add a basic help string) which should not be difficult because the commands are quite simple. Only a question of time.

It's easier for me to do this when working on the unittests of pacli, that's the reason I put this on hold. The vanilla commands should have unittests already, so what I would do is to revise the unittests if they also fail like in your bug reports, and then fix both unittests and the code if the bug is confirmed.

**Comment by d5000** [comment] 2024-08-19 05:13
I'm closing this because after having thought again about it I don't see an easy way to implement it. Vanilla commands will of course later be fixed.

**Closed by d5000** 2024-08-19 05:13 UTC
Labels: question
