### ISSUE TITLE
How is the end of proposal's period calculated?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#177] opened 2024-08-07 09:54 UTC
I've run `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432 D1 -e` and got `141155`.
However the output of `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432` command  mentions `(start: 141232, end: End of chain)`, while the block `141155` seems to match the `Period D1: Voting Round 2`. 
So I was wondering how was the end of the proposal calculated in this case?

**Comment by d5000** [comment] 2024-08-07 18:58
I don't really understand your question?
The `-e` flag (end) seems to work correctly for period D1, if I use `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432 -a` I get the correct result for the period D1.
Period E always lasts until the end of chain.

**Comment by buhtignew** [comment] 2024-08-08 13:03
It's possible I've misunderstood something here, but at the moment I'm not able to check it because if I run `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432 D1 -e` I'm getting:
```
General error raised by PeerAssets. Check if your input is correct.
```
Maybe with the last upgrade something has been changed in the code in this case?

**Comment by d5000** [comment] 2024-08-08 19:51
Indeed there was another oversight yesterday. Fixed in commit c441440.

**Comment by buhtignew** [comment] 2024-08-09 12:48
I've checked my own question again and I think the question was: in case the code needs to use the final end block of the proposal for any reason, what block is being used?
In the mean time I've got a little bit more used with this group of commands and I've seen that is some context the next block after the current one is considered as a kind of the end block of the moment, for instance the `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432` command outputs:
```
'Next block: 514570'
'Period E. Distribution finished (reward claiming allowed if proposal '
'was successful). (start: 141232, end: End of chain)'
```
Don't know whether my assumption is right in this case.
_
While I was checking the above I've also run `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432 E -e` and got:
```
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 479, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/dt_classes.py", line 615, in period
    return ei.run_command(self.__get_period, proposal_id, period, mode=mode, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_interface.py", line 34, in run_command
    result = c(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/dt_classes.py", line 662, in __get_period
    period_heights = periods[(pletter, pnumber)]
                                       ^^^^^^^
UnboundLocalError: cannot access local variable 'pnumber' where it is not associated with a value
```

**Comment by d5000** [comment] 2024-08-09 19:37
> I've seen that in some context the next block after the current one is considered as a kind of the end block of the moment [...]

Not really. The "next block" is only an indication of where the blockchain stands at this moment. It's the next block after the current block. This is because the calculation of the current period (i.e. the command without flags) is based on the next block, not the last block.

The logic behind is that if you're at the start of a voting round for example, you can already start voting one block before the period start, so it's appropiate that you see the period which begins with the next block. The same at the end of a period: if the last block has already been found, already your vote will be invalid.

The end block value for period E (in reality, E0, see below) is always void because the period will never end.

> UnboundLocalError

Good find. This is at least "unexpected behaviour". The reason is that in reality each period is a combination of a letter and a number. But the inconsistency is that if you use the `-a` option, E0 is shown only as "E".

I have solved it in the following way: In the periods E and C, with only one sub-period, the letters alone are accepted as an argument of `proposal period`, and they point to period E0 and C0. In the output of the `-a` option, however, "E0" is shown and not more "E", so it's consistent with period "C" which was already shown as "C0".

Commit for the improvement is 44ed955.

**Closed** 2024-08-10 06:25 UTC
Labels: question
