### ISSUE TITLE
 address list output

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#16] opened 2024-02-10 18:51 UTC
I've noticed that for the addresses without label the label column is now filled with
```
(unlabeled0)
(unlabeled1)
(unlabeled2)
(unlabeled3)...
``` 
While previously it was empty. Is it an intended change in code?

**Comment by d5000** [comment] 2024-02-11 03:10
Yes, this is intended.
Which output do you think is better? I can suppress the table to show these "unlabeled" labels.

**Comment by buhtignew** [comment] 2024-02-12 08:09
I think both are good, but probably if there is no label at all it's already self-descriptive. So I'm slightly pending in favor of the former.

**Comment by d5000** [comment] 2024-02-27 20:06
Unlabeled is gone now. Commit 75d2033. I'm closing as this was not a bug report.

**Comment by buhtignew** [comment] 2024-02-28 08:36
I'm still seeing the unlabeled's in the `address list -a` output, is it intended?
If so please close this issue again.

**Comment by d5000** [comment] 2024-02-28 17:32
You're correct. I'm currently working on another issue so the commit will come later (once you see an upgrade of another thread, the "unlabeled" will also be gone from the `-a` view).

BTW: to reopen an issue you have to click on "reopen with comment", not on "Comment". Otherwise I'll not see them as open. You were lucky today because I was just checking the closed list too ... I'm reopening but if later everything worked as expected you should close it again.

**Closed** 2024-02-29 17:03 UTC
Labels: question
