### ISSUE TITLE
transaction set with -m doesn't work anymore?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#141] opened 2024-07-08 19:10 UTC
I've re-tested `transaction set` with the `-m` flag.

Here is my `transaction list -n` output:
```
{
    'my_new_label':
        '0100000026e2786202b62fcc1263444135f054f431fa8e16468cdc5cf9ab03480e4d3'
        'a2341993dd8b3010000006a4730440220258dc6a7483da7f2593f4278da7df2d5ec01'
        '3b1e51164b4db155b95dba8d93e602202196bda347d2fd7300385dc04e55b8586796f'
        '9133956bf36be8bc8fc381d56e8012103103c38266931ffdea961ab58a4be89710953'
        'a0e62186856ed7f3f695a1db421effffffff2c5219036db6a6b092f2b5718c88e2271'
        '95918864dfff48fbb87a4a3bc0daef8010000006b483045022100900a647d8320d163'
        '6323317c97be7e12a188ded29e19b182254c94891705a93202201dc6b19f29f3aa1ed'
        'a8de082561c770c7e0b986af0eb8a5ae19460b082750f19012103103c38266931ffde'
        'a961ab58a4be89710953a0e62186856ed7f3f695a1db421effffffff0410270000000'
        '000001976a9145fbb9fb88a64bf226051d5797f5db46c3afc710c88ac102700000000'
        '0000246a22445342895a6f8aaffbb3e26f776e747c8251ef01d80a6a526bc5199f083'
        'f7f4356fa0050d6dc010000001976a914b5a2ced9afd823cb142607e2d4e7e979cb73'
        'b87f88acd0549a3b000000001976a914becdce1f2621cd5ad2f8ba27a037fa056d28e'
        '6c288ac00000000'
}
{
    'new': 'f4e26f3a14a7fbe7ea45bd60ad9005ebbaa36a3cecd864c7f3ef517c5fe27c86'
}
{
    'second_one':
        '01000000b317de6401000000000000000000000000000000000000000000000000000'
        '0000000000000ffffffff0e04b317de640101062f503253482fffffffff01e03caa06'
        '00000000232103f0ef2f8702b64da8da1481959a4486b16b94614831e194b2ebfdf8f'
        '11c764a85ac00000000'
}
{
    'third_one':
        '0100000026e2786202b62fcc1263444135f054f431fa8e16468cdc5cf9ab03480e4d3'
        'a2341993dd8b3010000006a4730440220258dc6a7483da7f2593f4278da7df2d5ec01'
        '3b1e51164b4db155b95dba8d93e602202196bda347d2fd7300385dc04e55b8586796f'
        '9133956bf36be8bc8fc381d56e8012103103c38266931ffdea961ab58a4be89710953'
        'a0e62186856ed7f3f695a1db421effffffff2c5219036db6a6b092f2b5718c88e2271'
        '95918864dfff48fbb87a4a3bc0daef8010000006b483045022100900a647d8320d163'
        '6323317c97be7e12a188ded29e19b182254c94891705a93202201dc6b19f29f3aa1ed'
        'a8de082561c770c7e0b986af0eb8a5ae19460b082750f19012103103c38266931ffde'
        'a961ab58a4be89710953a0e62186856ed7f3f695a1db421effffffff0410270000000'
        '000001976a9145fbb9fb88a64bf226051d5797f5db46c3afc710c88ac102700000000'
        '0000246a22445342895a6f8aaffbb3e26f776e747c8251ef01d80a6a526bc5199f083'
        'f7f4356fa0050d6dc010000001976a914b5a2ced9afd823cb142607e2d4e7e979cb73'
        'b87f88acd0549a3b000000001976a914becdce1f2621cd5ad2f8ba27a037fa056d28e'
        '6c288ac00000000'
}
```

I've tried to rename all of my labels by running `transaction set third_one1 third_one -m`, `transaction set third_one third_one1 -m`, `transaction set second_one1 second_one -m`, `transaction set second_one second_one1 -m`, `transaction set new1 new -m`, `transaction set new new1 -m`,  `transaction set abracadabra my_new_label -m` and `transaction set  my_new_label another_one -m` commands and each time got the following output:
```
        General error raised by PeerAssets. Check if your input is correct.

        If you gave a deck as an argument, a possible reason for this error is that you need to initialize the deck.

        To initialize the default decks, use:

        pacli deck init

        To initialize a single deck, use:

        pacli deck init DECKID
```
I'm not able to post my debug output since we don't the appropriate flag for `transaction set` command.

What am I doing wrong in this case?

**Comment by d5000** [comment] 2024-07-24 04:18
Confirmed and fixed in commit 400bad8, this was a bug in one of the last modifications of that command.
I also added `-s` or `--show_debug_info` parameter as in some other commands.
Closing because the bug was quite obvious, if you get problems please reopen.

**Comment by buhtignew** [comment] 2024-07-24 08:37
The commit works fine.

The only thing is that I'm not seeing the `--show_debug_info` flag in the list of flags of the help, but if it were there it would be conflicting with the `--sent` flag, I guess.

**Comment by d5000** [comment] 2024-07-24 16:06
The -s flag is for transaction set, where no debug option was given before, not for transaction list. Closing again, please only re-open if there is a new problem.

**Closed by d5000** 2024-07-24 16:06 UTC
Labels: anomaly
