### ISSUE TITLE
donation list DECK -m testing

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#113] opened 2024-06-05 08:38 UTC
In agreement to the Usage mode mentioned in the `donation list -h` I've run `donation list a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a -m`, `donation list 3369f3eb703656c0b46b613dcfb4df78fc05657a0b75f44551634de6321d9d9c -m` and `donation list 0b3816628374d24078c741251f712b7f6af1c6f82ff7ddce083c20a58fcc2bc1 -m` for all the PoD tokens from my `token list -p` output but each time I've got the following error:
```
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 479, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/dt_classes.py", line 1010, in list
    return ei.run_command(dc.show_donations_by_address, deckid, examine_address, mode=mode)
                                                                                      ^^^^
UnboundLocalError: cannot access local variable 'mode' where it is not associated with a value
```

**Comment by d5000** [comment] 2024-06-09 06:39
Fixed in commit 5a37a0b.

**Comment by buhtignew** [comment] 2024-06-10 07:39
Everything seems to work as expected, the only strange thing I'm seeing is the output of `donation list 0b3816628374d24078c741251f712b7f6af1c6f82ff7ddce083c20a58fcc2bc1 -m` command:
```
'Donations realized from address: mixcqdAy4aFtuBV7uRebqBTjiFWCcS4UEp'
 
        General error raised by PeerAssets. Check if your input is correct.

        If you gave a deck as an argument, a possible reason for this error is that you need to initialize the deck.

        To initialize the default decks, use:

        pacli deck init

        To initialize a single deck, use:

        pacli deck init DECKID
```
I've tried with `donation list 0b3816628374d24078c741251f712b7f6af1c6f82ff7ddce083c20a58fcc2bc1 -m -d`, but the output hasn't changed.

**Comment by d5000** [comment] 2024-06-10 20:06
I can't reproduce the error. 

I saw that I had forgot the debug mode for one of the branches of this command. I have now added a debug mode. Can you repeat your command with the updated code?

I also added the `--wallet` or `-w` option for the `-m` branch without `-p`. This was an easy addition and already in my TODO list. So now it's possible to see all donations from the wallet with one command, regardless of the proposal, so I consider it an important improvement.

Commit: 63f387e

**Comment by buhtignew** [comment] 2024-06-11 07:48
> I consider it an important improvement.

It is indeed!

> I saw that I had forgot the debug mode for one of the branches of this command. I have now added a debug mode. Can you repeat the command which led to the error (with -d of course) with the updated code?

The error hasn't gone away on my side. However, I think I've got the meaning of this message.
The deck wasn't initialized. Maybe we should decide whether to provide the same output for the decks that are not initialized as for those initialized or to not provide any output and to throw the error.

**Comment by d5000** [comment] 2024-07-08 23:24
Ah, you could have written that the deck was not initialized.
I see no reason why to change something. The message then exactly does what it has to do. Closing.

**Closed by d5000** 2024-07-08 23:24 UTC
Labels: error message
